#!/bin/sh
[ "${IPKG_NO_SCRIPT}" = "1" ] && exit 0
[ -s ${IPKG_INSTROOT}/lib/functions.sh ] || exit 0
. ${IPKG_INSTROOT}/lib/functions.sh
default_postinst $0 $@
if [ -f /etc/uci-defaults/luci-app-remotbot ]; then
    sh /etc/uci-defaults/luci-app-remotbot && rm -f /etc/uci-defaults/luci-app-remotbot
fi
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache/ 2>/dev/null || true
echo "==========================="
echo " LuCI Remot Bot Installed!"
echo " Go: Services > Remot Bot"
echo "==========================="
exit 0
